# .github/workflows/shared/check-up-to-date.yml
name: Check if Branch is Up-to-Date

on:
  workflow_call:
    inputs:
      base_branch:
        description: 'The base branch to compare against (e.g., main)'
        required: true
        type: string
      repo:
        description: 'The repository name (e.g., h3-api-gateway)'
        required: true
        type: string

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest
    outputs:
      is_up_to_date: ${{ steps.check_branch.outputs.is_up_to_date }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for accurate comparisons
          repository: H3aven-Labs/${{ inputs.repo }}
          token: ${{ secrets.H3_NPM_TOKEN }}
          path: repo

      - name: Check if the branch is up-to-date with base
        id: check_branch
        run: |
          cd repo
          BASE_BRANCH=${{ inputs.base_branch }}
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git fetch origin ${{ inputs.base_branch }}

          # Check if CURRENT_BRANCH is behind BASE_BRANCH
          if git merge-base --is-ancestor origin/$BASE_BRANCH HEAD; then
            echo "::set-output name=is_up_to_date::true"
            exit 1
          else
            echo "::set-output name=is_up_to_date::false"
          fi
